name: Test apworld
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 1
      matrix:
        directory:
          - 'manual_ffdissidia_silasary'
          - 'manual_siivagunner_silasary'
          - 'manual_melbournetrains_silasary'
    steps:
      - uses: Eijebong/ap-actions/ap-tests@main
        with:
          apworld-path: ${{ matrix.directory }}
          ap-version: latest
          python-version: '3.13'
