on:
    workflow_dispatch:
    schedule:
      - cron: 0 0 1 * * # Runs at 00:00 on the first day of every month


jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        directory:
          - 'manual_ffdissidia_silasary'
          - 'manual_siivagunner_silasary'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update manual
        uses: ./update-manual
        with:
          allow_unstable: 'true'
          directory: ${{ matrix.directory }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update manual to latest version
          branch: update-manual-${{ matrix.directory }}
          labels: automated-pr
